"""`plasmon server init --bundle compose`: write a Docker Compose deployment.

Files: docker-compose.yml, Caddyfile, .env (secrets), plasmon-server.yaml. The API and
the scheduler run from the same image. PostgreSQL and MinIO hold the state; Caddy
terminates TLS.
"""

from __future__ import annotations

import secrets
from pathlib import Path

from .config import BlobStoreConfig, ServerConfig

IMAGE = "ghcr.io/edumntg/plasmon"


def compose_yaml(domain: str, with_minio: bool, with_postgres: bool, replicas: int = 1) -> str:
    db_url = "postgresql+psycopg://plasmon:${POSTGRES_PASSWORD}@postgres:5432/plasmon" if with_postgres else "${PLASMON_DB_URL}"
    common_env = f"""      PLASMON_DB_URL: "{db_url}"
      PLASMON_PUBLIC_URL: "https://{domain}"
      PLASMON_SESSION_SECRET: "${{PLASMON_SESSION_SECRET}}"
      PLASMON_S3_ACCESS_KEY: "${{S3_ACCESS_KEY}}"
      PLASMON_S3_SECRET_KEY: "${{S3_SECRET_KEY}}"
      PLASMON_OIDC_CLIENT_SECRET: "${{OIDC_CLIENT_SECRET}}"
      PLASMON_SMTP_PASSWORD: "${{PLASMON_SMTP_PASSWORD}}\""""
    depends = []
    if with_postgres:
        depends.append("postgres")
    if with_minio:
        depends.append("minio")
    depends_yaml = ("    depends_on:\n" + "".join(f"      - {d}\n" for d in depends)) if depends else ""
    out = f"""# plasmon, generated by `plasmon server init --bundle compose`
# Start:   docker compose up -d
# Logs:    docker compose logs -f api worker
# Update:  docker compose pull && docker compose up -d
services:
  api:
    image: {IMAGE}:${{PLASMON_VERSION:-latest}}
    restart: unless-stopped
    command: ["python", "-m", "plasmon.coordinator", "/config/plasmon-server.yaml"]
    environment:
      PLASMON_RUN_WORKER: "0"
{common_env}
    volumes:
      - ./plasmon-server.yaml:/config/plasmon-server.yaml:ro
      - server-data:/data
    deploy:
      replicas: {replicas}
{depends_yaml}
  worker:
    image: {IMAGE}:${{PLASMON_VERSION:-latest}}
    restart: unless-stopped
    command: ["python", "-m", "plasmon.coordinator.worker", "/config/plasmon-server.yaml"]
    environment:
{common_env}
    volumes:
      - ./plasmon-server.yaml:/config/plasmon-server.yaml:ro
      - server-data:/data
{depends_yaml}
  caddy:
    image: caddy:2
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
      - "443:443/udp"
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile:ro
      - caddy-data:/data
      - caddy-config:/config
    depends_on:
      - api
"""
    if with_postgres:
        out += """
  postgres:
    image: postgres:16
    restart: unless-stopped
    environment:
      POSTGRES_DB: plasmon
      POSTGRES_USER: plasmon
      POSTGRES_PASSWORD: "${POSTGRES_PASSWORD}"
    volumes:
      - postgres-data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U plasmon"]
      interval: 10s
      timeout: 5s
      retries: 10
"""
    if with_minio:
        out += """
  minio:
    image: minio/minio
    restart: unless-stopped
    command: server /data --console-address ":9001"
    environment:
      MINIO_ROOT_USER: "${S3_ACCESS_KEY}"
      MINIO_ROOT_PASSWORD: "${S3_SECRET_KEY}"
    volumes:
      - minio-data:/data
    healthcheck:
      test: ["CMD", "curl", "-f", "http://127.0.0.1:9000/minio/health/live"]
      interval: 10s
      timeout: 5s
      retries: 10

  minio-init:
    image: minio/mc
    depends_on:
      - minio
    entrypoint: >
      /bin/sh -c "
      until mc alias set local http://minio:9000 $$S3_ACCESS_KEY $$S3_SECRET_KEY; do sleep 2; done;
      mc mb --ignore-existing local/plasmon;
      exit 0"
    environment:
      S3_ACCESS_KEY: "${S3_ACCESS_KEY}"
      S3_SECRET_KEY: "${S3_SECRET_KEY}"
"""
    out += """
volumes:
  server-data:
  caddy-data:
  caddy-config:
"""
    if with_postgres:
        out += "  postgres-data:\n"
    if with_minio:
        out += "  minio-data:\n"
    return out


def caddyfile(domain: str, tls_internal: bool) -> str:
    tls = "  tls internal\n" if tls_internal else ""
    return f"""{domain} {{
{tls}  encode zstd gzip
  reverse_proxy api:7117
}}
"""


def write_bundle(directory: Path, cfg: ServerConfig, domain: str, storage: str, db_url: str | None, tls_internal: bool = False, replicas: int = 1) -> list[Path]:
    """Return the files written. `storage` is `minio` or `s3://bucket[@endpoint]`."""
    directory.mkdir(parents=True, exist_ok=True)
    with_postgres = db_url is None
    with_minio = storage == "minio"
    if with_minio:
        cfg.blobs = BlobStoreConfig(kind="s3", bucket="plasmon", endpoint_url="http://minio:9000")
    elif storage.startswith("s3://"):
        rest = storage[len("s3://"):]
        bucket, _, endpoint = rest.partition("@")
        cfg.blobs = BlobStoreConfig(kind="s3", bucket=bucket, endpoint_url=endpoint or None)
    else:
        raise ValueError("storage must be `minio` or `s3://bucket[@https://endpoint]`")
    cfg.public_url = f"https://{domain}"
    cfg.host = "0.0.0.0"
    cfg.port = 7117
    cfg.data_dir = "/data"
    cfg.db_url = None  # set through PLASMON_DB_URL in compose
    env_lines = [
        f"PLASMON_SESSION_SECRET={secrets.token_hex(32)}",
        f"POSTGRES_PASSWORD={secrets.token_urlsafe(24)}" if with_postgres else f"PLASMON_DB_URL={db_url}",
        f"S3_ACCESS_KEY={'plasmon' if with_minio else ''}",
        f"S3_SECRET_KEY={secrets.token_urlsafe(24) if with_minio else ''}",
        "OIDC_CLIENT_SECRET=",
        "PLASMON_SMTP_PASSWORD=",
        "PLASMON_VERSION=latest",
    ]
    files = {
        "docker-compose.yml": compose_yaml(domain, with_minio, with_postgres, replicas),
        "Caddyfile": caddyfile(domain, tls_internal),
        ".env": "\n".join(env_lines) + "\n",
    }
    written = []
    for name, text in files.items():
        p = directory / name
        p.write_text(text, encoding="utf-8")
        if name == ".env":
            try:
                p.chmod(0o600)
            except OSError:
                pass
        written.append(p)
    from . import config as config_mod

    written.append(config_mod.write(cfg, directory / "plasmon-server.yaml"))
    return written
